apiVersion: v1
kind: Service
metadata:
  labels:
    run: solicitations-node
    name: solicitations-node-service
  name: solicitations-node-service
spec:
  ports:
  - nodePort: 30334
    # The port that this service should serve on.
    port: 3334
    protocol: TCP
    targetPort: 3334
    nodePort: 30334
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    run: solicitations-node
  type: NodePort
