apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: solicitations-node
  name: solicitations-node
spec:
  replicas: 3
  selector:
    matchLabels:
      run: solicitations-node
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: solicitations-node
    spec:
      containers:
      - image: $DNAME:443/solicitations-node:v1
        name: solicitations-node
        imagePullPolicy: Always
        resources: {}
status: {}
