kind: PersistentVolume
apiVersion: v1
metadata:
  name: nress-git-ssh-pv-volume
  labels:
    type: local
spec:
  storageClassName: tsa
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/tsa/.ssh