# This file is combined service and deployment yaml. No need to run
# two separate yamls
# 384 is octal for 0600 permission
# - mkdir -p /home/tsa/.ssh && chmod 700 /home/tsa/.ssh && cat {{ .Values.nressGit.sshKeyPub | b64enc | quote }} > /home/tsa/.ssh/authorized_keys && chmod 644 /home/tsa/.ssh/authorized_keys && sleep 43200

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: nress-git
  name: nress-git
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nress-git
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nress-git
    spec:
      volumes:
        - name: nress-git-storage
          persistentVolumeClaim:
           claimName: nress-git-pv-claim    
        - name: nress-git-ssh-key
          hostPath:
            path: /home/tsa/.ssh
      containers:
      - image: ubt-master:443/nress-git:v1
        name: nress-git
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args: 
          - mkdir -p /home/tsa/.ssh && chown tsa:tsa /home/tsa/.ssh && chmod 700 /home/tsa/.ssh && echo {{ .Values.nressGit.sshKeyPub | quote }} > /home/tsa/.ssh/authorized_keys && chown tsa:tsa /home/tsa/.ssh/authorized_keys && chmod 644 /home/tsa/.ssh/authorized_keys && service sshd restart; sleep 43200
        resources: {}
        volumeMounts:
          - mountPath: "/nress-git"
            name: nress-git-storage
          - mountPath: "/keys/ssh"
            name: nress-git-ssh-key
            readOnly: true
status: {}