# This file is combined service and deployment yaml. No need to run
# two separate yamls
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-node
  labels:
    app: users-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users-node
  template:
    metadata:
      labels:
        app: users-node
    spec:
      containers:
      - image: "{{ .Values.image.url }}:{{ .Values.image.port }}/users-node:{{ .Values.image.version }}"
        name: users-node
        imagePullPolicy: Always
        resources: {}
