# This file is combined service and deployment yaml. No need to run
# two separate yamls
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: reviews-node
  name: reviews-node
spec:
  replicas: 3
  selector:
    matchLabels:
      run: reviews-node
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: reviews-node
    spec:
      containers:
      - image: ubt-master:443/reviews-node:v1
        name: reviews-node
        imagePullPolicy: Always
        resources: {}
status: {}